### ISSUE TITLE
"ibm-mq" EC2 instance stuck in "Terminating"-->"Running" loop.

### ISSUE THREAD

**Issue by lpaf** [aws-quickstart/quickstart-ibm-mq#15]
Hello,

Following your deployment guide, I have deployed IBM MQ to an existing VPC, on my AWS account.
The stack created processed was successfully done, without any visible error. However, the new created bastion host "ibm-mq", keeps getting terminated and then re-created again. On both the created Classic LB and NLB, nothing is being registered.
Any suggestions on how to debug this issue?

**Comment by punitporwal07** [comment]
Hello IBM,

Do we have any update on the subjected issue?
Even today the stack creation was successfully done, however, EC2 instance keeps getting terminated possibly due to health check failure @ ping 1414 and classic load balancer removes the host from the equation and autoscaling keeps on recreating a new ec2-instance.

One thing I observed here is - your documents says it will create 2 Autoscaling group where as in the CF-template there is reference of only 1 autoscaling group which eventually create only 1 for me post completion.

Kindly suggest ; TIA

**Comment by jmcguire23** [comment]
Hi @punitporwal07,

I have just run  deployment of the full quickstart template and was not able to reproduce this particular issue.

To help identify the problem can you confirm which template was used; 'Deploy IBM MQ into a new VPC on AWS' or 'Deploy IBM MQ into an existing VPC on AWS'?

https://aws-quickstart.github.io/quickstart-ibm-mq/#_launch_the_quick_start

Deploying the [quickstart master template](https://github.com/aws-quickstart/quickstart-ibm-mq/blob/main/templates/ibm-mq-master.template) will deploy a new VPC environment and Bastion host configuration using the submodules connected to this repository. 

If you choose to deploy into an [existing VPC on AWS](https://github.com/aws-quickstart/quickstart-ibm-mq/blob/main/templates/ibm-mq.template), it assumes you have a VPC environment configured with at least two public and private subnets, and have installed bastion hosts to this environment. This template requires more details to configure with your existing environment, [see here](https://aws-quickstart.github.io/quickstart-ibm-mq/#_parameters_for_launching_into_an_existing_vpc).

In EC2, click ibm-mq in the table. In the instance details section below you should see a Monitoring tab, click on this to view monitoring charts. You should be able to see two charts titled "Status check failed (any) (count)" and "Status check failed (instance) (count)". Are these reporting any failures?

**Comment by punitporwal07** [comment]
I choose to 'Deploy IBM MQ into an existing VPC on AWS'
Yes I do have an existing VPN with two Private and two Public subnet placed in two different AZ.

Also I do not see any failure in monitoring tabs. However if I check the activity history of scaling group I see some failure being captured, attached is the screenshot fyr.
![image](https://user-images.githubusercontent.com/30653869/134287867-89ae4b59-4813-48f7-bd85-319d416698b8.png)

**Comment by jmcguire23** [comment]
The elastic load balancer is configured to run a ping health check on listener port 1414.  Have you removed or changed the listener configuration in your queue manager?

**Comment by punitporwal07** [comment]
No, it is as is.
![image](https://user-images.githubusercontent.com/30653869/134308205-86d250fe-cc8c-4ff3-9d31-14360f21fb06.png)

**Comment by jmcguire23** [comment]
I would recommend checking the system logs for the ibm-mq EC2 instance.

**Comment by punitporwal07** [comment]
Here is the system log for one the recently terminated instance, please find.
[i-0370c6112d3b0308a.log](https://github.com/aws-quickstart/quickstart-ibm-mq/files/7209317/i-0370c6112d3b0308a.log)

**Comment by jmcguire23** [comment]
I have not been able to reproduce this issue following the instructions from our documentation. 

I would suggest that your log output does not show the queue manager startup process commencing, which suggests that the problem is within your AWS infrastructure configuration. I would assume that based on using the deployment into an existing VPC environment you may need to inspect your subnet configuration and compare with the [aws-vpc template](https://github.com/aws-quickstart/quickstart-aws-vpc/blob/c89deff157bdf59bb159878ebdaea53ae6753759/templates/aws-vpc.template.yaml).

You might want to try the full deployment template by choosing to  deploy into a new VPC in AWS [here](https://aws-quickstart.github.io/quickstart-ibm-mq/#_launch_the_quick_start). This will create a VPC and Bastion host environment based on the aws quickstart templates provided, which is good reference architecture to use as a baseline for your AWS deployment.

**Comment by jmcguire23** [comment]
@punitporwal07 One final suggestion to diagnose the problem further I would suggest changing the settings to the maximum values allowed, and monitor the startup of your instance.

![Screenshot 2021-09-22 at 11 29 25](https://user-images.githubusercontent.com/5710033/134328046-98902b79-ddcd-4fe1-9a9a-324842f63834.png)

@vsnyc Any further suggestions how to diagnose this problem?

**Comment by vsnyc** [comment]
Closing old issues. The solution has been updated to use [IBM MQ Helm chart](https://github.com/ibm-messaging/mq-helm) for deployment.
